#!/bin/bash

cd "$1../" || exit 1

source .env

DEFAULT_DV_INSTALL_DIR="$HOME/.local/share/Steam/steamapps/common/Derail Valley"

if [[ -z "$DV_INSTALL_DIR" ]]; then
  echo "No DV_INSTALL_DIR environment variable found. Assuming '$DEFAULT_DV_INSTALL_DIR'"
  DV_INSTALL_DIR="$DEFAULT_DV_INSTALL_DIR"
fi

if [[ ! -d "$DV_INSTALL_DIR" ]]; then
  echo "Derail Valley installation directory '$DV_INSTALL_DIR' does not exist. Exiting."
  exit 1
fi

DERAIL_VALLEY_EXE="DerailValley.exe"

if [ ! -f "$DV_INSTALL_DIR/$DERAIL_VALLEY_EXE" ]; then
  echo "Derail Valley installation directory '$DV_INSTALL_DIR' does not contain $DERAIL_VALLEY_EXE. Is it the correct path?"
  exit 1
fi

./package || exit 1

cp -r BepInEx "$DV_INSTALL_DIR"
