site_name: Mapify
site_description: Documentation for Mapify

site_url: https://dv-mapify.rtfd.io/
repo_name: insprill/dv-mapify
repo_url: https://github.com/Insprill/dv-mapify/
edit_uri: blob/master/docs/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  - pymdownx.caret
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Using Maps:
        - usage/index.md
  - Creating Maps:
        - Project Setup: creatingmaps/project-setup.md
        - Terrain: creatingmaps/terrain.md
        - Decoration: creatingmaps/decoration.md
        - Railway: creatingmaps/railway.md
        - Job Generation: creatingmaps/jobs.md
        - Area Blockers: creatingmaps/area-blockers.md
        - Service Stations: creatingmaps/service-stations.md
        - Stores: creatingmaps/stores.md
        - Lighting & Post Processing: creatingmaps/lighting.md
        - Exporting Your Map: creatingmaps/exporting.md
        - Updating Mapify: creatingmaps/updating.md
  - Contributing:
      - contributing/index.md
      - Building The Project: contributing/building.md
      - Building Documentation: contributing/docs.md
