#!/bin/bash

function check_file_exists() {
    if ! [ -e "$1" ]; then
        echo "Failed to find $1!"
        exit 1
    fi
}

ZIP_STRUCTURE=BepInEx/plugins/Mapify/
LICENSE_FILE="LICENSE"
LOCALE_FILE="locale.csv"
MAPIFY_DLL="build/Mapify.dll"
MAPIFY_EDITOR_DLL="build/MapifyEditor.dll"
VERSION=$(grep -Eo '"([0-9]+\.[0-9]+\.[0-9]+")' Mapify/Mapify.cs | sed 's/"//g')

check_file_exists "$LICENSE_FILE"
check_file_exists "$LOCALE_FILE"
check_file_exists "$MAPIFY_DLL"
check_file_exists "$MAPIFY_EDITOR_DLL"

mkdir -p $ZIP_STRUCTURE
cp -pfu $LICENSE_FILE $LOCALE_FILE $MAPIFY_DLL $MAPIFY_EDITOR_DLL $ZIP_STRUCTURE

FILE_NAME="Mapify_v$VERSION.zip"
zip -1 -T -u "$FILE_NAME" $ZIP_STRUCTURE*
echo "$FILE_NAME"
